In [1]:
#EXP NO:05

In [2]:
# Aim: Creation of arrays using numpy

In [3]:
#Name: Sarthaki Wanjari
#Roll no: 66
#subject: ET -1
#Sec: C
#Date: 29/08/2025

In [4]:
import numpy as np

In [5]:
#creating 1D array. (square bracket in round = array)(square bracket=tuple)
a1=np.array([60,10,50,10])

In [6]:
a1

array([60, 10, 50, 10])

In [7]:
#creating 2D array 
a2 = np.array([[11,22,18,24],[41,35,40,55]])

In [8]:
a2

array([[11, 22, 18, 24],
       [41, 35, 40, 55]])

In [9]:
#creating 2D array using matrix
a3=np.matrix('11,23;33,45;67,78')
print(a3)

[[11 23]
 [33 45]
 [67 78]]


In [10]:
# Create array of 25 random integers between 20 and 23 (inclusive)
arr = np.random.randint(20, 24, size=25)
print(arr)

[23 23 23 20 22 21 20 21 22 22 23 22 21 20 21 21 20 23 21 22 21 22 21 23
 23]
